// apps/mobile/app/(org-admin)/settings/_components/change-scope-wizard.tsx
import { useState } from 'react';
import { View, Text, Pressable, ScrollView, ActivityIndicator, StyleSheet, TextInput } from 'react-native';
import { useMutation } from '@tanstack/react-query';
import { OrgConfigService } from '@/features/org/services/org-config.service';
import {
  OrgCenteredModal,
} from '@/shared/components/org-centered-modal';
import { Icon } from '@/shared/components/icon/icon';
import { colors, colorScales, spacing, typography, borderRadius } from '@/shared/theme';
import {
  scopeShortLabel,
  blockerTitle,
  directionArrow,
  forceReasonRemaining,
  isForceReasonValid,
  type BlockerLike,
} from '@/features/org/components/operating-scope-formatters';
import type {
  OperatingScopeValue,
  OperatingScopePreview,
  OperatingScopeApplyResult,
  OperatingScopeBlocker,
} from '@/core/models/org-admin/config.types';
import { toastSuccess } from '@/shared/components/toast/toast.store';

/**
 * Wizard de cambio de modo operativo (paridad visual con web).
 * 4 pasos:
 *   1 — Confirmar intención (current vs target + razón opcional).
 *   2 — Preview (blockers + warnings).
 *   3 — Force-confirm (solo cuando hay blockers DOWN y no son PARTNER_LOCKED).
 *   4 — Result (success o error).
 */
type WizardStep = 1 | 2 | 3 | 4;

interface ChangeScopeWizardProps {
  visible: boolean;
  currentScope: OperatingScopeValue;
  targetScope: OperatingScopeValue;
  onClose: () => void;
  onApplied: (result: OperatingScopeApplyResult) => void;
}

export function ChangeScopeWizard({
  visible,
  currentScope,
  targetScope,
  onClose,
  onApplied,
}: ChangeScopeWizardProps) {
  const [step, setStep] = useState<WizardStep>(1);
  const [reason, setReason] = useState('');
  const [forceReason, setForceReason] = useState('');
  const [understandsConsequences, setUnderstandsConsequences] = useState(false);
  const [preview, setPreview] = useState<OperatingScopePreview | null>(null);
  const [previewError, setPreviewError] = useState<string | null>(null);
  const [applyError, setApplyError] = useState<string | null>(null);
  const [appliedResult, setAppliedResult] = useState<OperatingScopeApplyResult | null>(null);

  const reset = () => {
    setStep(1);
    setReason('');
    setForceReason('');
    setUnderstandsConsequences(false);
    setPreview(null);
    setPreviewError(null);
    setApplyError(null);
    setAppliedResult(null);
  };

  const handleClose = () => {
    onClose();
    setTimeout(reset, 250);
  };

  // ---------- preview mutation ----------
  const previewMutation = useMutation({
    mutationFn: async () => {
      return OrgConfigService.previewOperatingScope(targetScope, reason);
    },
    onSuccess: (data) => {
      setPreview(data);
      setStep(2);
    },
    onError: (err: any) => {
      setPreviewError(extractErrorMessage(err, 'No se pudo obtener el preview del cambio.'));
    },
  });

  // ---------- apply mutation ----------
  const applyMutation = useMutation({
    mutationFn: async ({ force }: { force: boolean }) => {
      const reasonToSend = force ? forceReason.trim() : reason;
      return OrgConfigService.applyOperatingScope(targetScope, reasonToSend, force);
    },
    onSuccess: (result) => {
      setAppliedResult(result);
      setStep(4);
      toastSuccess(
        result.forced
          ? 'Cambio aplicado (forzado)'
          : 'Modo operativo actualizado',
      );
      onApplied(result);
    },
    onError: (err: any) => {
      setApplyError(extractErrorMessage(err, 'No se pudo aplicar el cambio.'));

      // 409 with blockers → refresh preview and return to step 2
      const status = err?.status ?? err?.response?.status;
      const blockers = err?.error?.blockers ?? err?.response?.data?.blockers;
      if (status === 409 && Array.isArray(blockers) && preview) {
        setPreview({
          ...preview,
          blockers,
          can_apply: false,
        });
        setStep(2);
      }
    },
  });

  // ---------- gates ----------
  const canShowForceOption =
    !!preview &&
    preview.blockers.length > 0 &&
    preview.direction === 'DOWN' &&
    !preview.blockers.some((b) => b.code === 'PARTNER_LOCKED');

  const canApply = !!preview && preview.can_apply && preview.blockers.length === 0;

  const canForceApply = understandsConsequences && isForceReasonValid(forceReason);

  const reasonRemaining = forceReasonRemaining(forceReason);

  // ---------- handlers ----------
  const goToPreview = () => {
    setPreviewError(null);
    setPreview(null);
    previewMutation.mutate();
  };

  const applyStandard = () => {
    if (!canApply) return;
    setApplyError(null);
    applyMutation.mutate({ force: false });
  };

  const goToForceConfirm = () => {
    if (!canShowForceOption) return;
    setApplyError(null);
    setUnderstandsConsequences(false);
    setForceReason('');
    setStep(3);
  };

  const forceApply = () => {
    if (!canForceApply) return;
    setApplyError(null);
    applyMutation.mutate({ force: true });
  };

  // ---------- render helpers ----------
  const renderStepDots = () => (
    <View style={styles.stepDotsRow}>
      {[1, 2, 3, 4].map((n) => {
        const isActive = n === step;
        const isPast = n < step;
        return (
          <View
            key={n}
            style={[
              styles.stepDot,
              isActive && styles.stepDotActive,
              isPast && styles.stepDotPast,
            ]}
          />
        );
      })}
    </View>
  );

  const renderStepLabel = () => {
    switch (step) {
      case 1:
        return 'Paso 1 de 4 · Confirmar intención';
      case 2:
        return 'Paso 2 de 4 · Vista previa';
      case 3:
        return 'Paso 3 de 4 · Confirmación forzada';
      case 4:
        return 'Paso 4 de 4 · Resultado';
    }
  };

  // ---------- step content ----------
  const renderStep1 = () => (
    <View>
      <Text style={styles.bodyText}>
        Vas a cambiar el modo operativo de la organización. Esta acción afecta cómo se gestiona el inventario, la contabilidad, las compras y los reportes.
      </Text>

      <View style={styles.summaryCard}>
        <View style={styles.summaryRow}>
          <Text style={styles.summaryLabel}>Modo actual</Text>
          <View style={styles.summaryValueWrap}>
            <Icon name="store" size={14} color={colorScales.gray[500]} />
            <Text style={styles.summaryValue}>{scopeShortLabel(currentScope)}</Text>
          </View>
        </View>
        <View style={styles.summaryArrow}>
          <Icon name="arrow-down" size={16} color={colors.primary} />
        </View>
        <View style={styles.summaryRow}>
          <Text style={styles.summaryLabel}>Modo destino</Text>
          <View style={styles.summaryValueWrap}>
            <Icon name="building-2" size={14} color={colors.primary} />
            <Text style={styles.summaryValueStrong}>{scopeShortLabel(targetScope)}</Text>
          </View>
        </View>
      </View>

      <Text style={styles.label}>Razón (opcional)</Text>
      <TextInput
        style={styles.textarea}
        placeholder="Describe brevemente por qué necesitas cambiar el modo operativo…"
        placeholderTextColor={colorScales.gray[400]}
        value={reason}
        onChangeText={setReason}
        multiline
        numberOfLines={3}
      />

      {previewError ? (
        <View style={styles.errorBox}>
          <Icon name="alert-circle" size={16} color={colorScales.red[600]} />
          <Text style={styles.errorText}>{previewError}</Text>
        </View>
      ) : null}
    </View>
  );

  const renderStep2 = () => {
    if (!preview) return null;

    const blockerList = preview.blockers ?? [];
    const warningList = preview.warnings ?? [];
    const hasBlockers = blockerList.length > 0;

    return (
      <View>
        <View style={styles.previewHeader}>
          <Text style={styles.previewDirection}>{directionArrow(currentScope, targetScope)}</Text>
          <View style={[styles.directionPill, preview.direction === 'DOWN' ? styles.directionPillDown : styles.directionPillUp]}>
            <Text style={styles.directionPillText}>
              {preview.direction === 'UP' ? 'UPGRADE' : preview.direction === 'DOWN' ? 'DOWNGRADE' : 'NOOP'}
            </Text>
          </View>
        </View>

        {warningList.length > 0 ? (
          <View style={styles.warningsBox}>
            <View style={styles.warningsHeader}>
              <Icon name="alert-triangle" size={14} color={colorScales.amber[700]} />
              <Text style={styles.warningsHeaderText}>Advertencias ({warningList.length})</Text>
            </View>
            {warningList.map((w, i) => (
              <Text key={i} style={styles.warningText}>• {w}</Text>
            ))}
          </View>
        ) : null}

        {hasBlockers ? (
          <View style={styles.blockersBox}>
            <View style={styles.blockersHeader}>
              <Icon name="x-circle" size={14} color={colorScales.red[600]} />
              <Text style={styles.blockersHeaderText}>
                Bloqueos ({blockerList.length})
              </Text>
            </View>
            {blockerList.map((b: OperatingScopeBlocker, i: number) => (
              <View key={i} style={styles.blockerRow}>
                <Text style={styles.blockerTitle}>{blockerTitle(b as BlockerLike)}</Text>
                <Text style={styles.blockerMessage}>{b.message}</Text>
              </View>
            ))}
          </View>
        ) : (
          <View style={styles.canApplyBox}>
            <Icon name="check-circle" size={16} color={colorScales.green[600]} />
            <Text style={styles.canApplyText}>No hay bloqueos — el cambio puede aplicarse.</Text>
          </View>
        )}

        {applyError ? (
          <View style={styles.errorBox}>
            <Icon name="alert-circle" size={16} color={colorScales.red[600]} />
            <Text style={styles.errorText}>{applyError}</Text>
          </View>
        ) : null}
      </View>
    );
  };

  const renderStep3 = () => (
    <View>
      <View style={styles.warningBanner}>
        <Icon name="alert-triangle" size={16} color={colorScales.amber[700]} />
        <Text style={styles.warningBannerText}>
          Estás a punto de forzar la migración ignorando los bloqueos del servidor. Esta acción queda registrada en el log de auditoría con tu razón.
        </Text>
      </View>

      <View style={styles.checkboxRow}>
        <Pressable
          style={[styles.checkbox, understandsConsequences && styles.checkboxChecked]}
          onPress={() => setUnderstandsConsequences(!understandsConsequences)}
          hitSlop={8}
        >
          {understandsConsequences ? (
            <Icon name="check" size={12} color="#fff" />
          ) : null}
        </Pressable>
        <Text style={styles.checkboxLabel}>
          Entiendo las consecuencias y autorizo el cambio forzado.
        </Text>
      </View>

      <Text style={styles.label}>
        Razón (mínimo {forceReasonRemaining('') === 0 ? 10 : 10} caracteres){' '}
        <Text style={styles.labelRequired}>obligatoria</Text>
      </Text>
      <TextInput
        style={styles.textarea}
        placeholder="Mínimo 10 caracteres. Ej: migración por cierre de bodega central…"
        placeholderTextColor={colorScales.gray[400]}
        value={forceReason}
        onChangeText={setForceReason}
        multiline
        numberOfLines={3}
      />
      <Text
        style={[
          styles.charCounter,
          reasonRemaining > 0 && styles.charCounterWarn,
        ]}
      >
        {reasonRemaining > 0
          ? `Faltan ${reasonRemaining} caracteres`
          : '✓ Listo para forzar'}
      </Text>

      {applyError ? (
        <View style={styles.errorBox}>
          <Icon name="alert-circle" size={16} color={colorScales.red[600]} />
          <Text style={styles.errorText}>{applyError}</Text>
        </View>
      ) : null}
    </View>
  );

  const renderStep4 = () => {
    if (applyError && !appliedResult) {
      return (
        <View style={styles.resultErrorBox}>
          <Icon name="x-circle" size={32} color={colorScales.red[600]} />
          <Text style={styles.resultErrorTitle}>No se pudo aplicar el cambio</Text>
          <Text style={styles.resultErrorMessage}>{applyError}</Text>
        </View>
      );
    }
    if (appliedResult) {
      return (
        <View style={styles.resultSuccessBox}>
          <Icon name="check-circle" size={32} color={colorScales.green[600]} />
          <Text style={styles.resultSuccessTitle}>
            Modo operativo actualizado
          </Text>
          <View style={styles.resultSummary}>
            <View style={styles.resultRow}>
              <Text style={styles.resultLabel}>Anterior</Text>
              <Text style={styles.resultValue}>{scopeShortLabel(appliedResult.previous_scope)}</Text>
            </View>
            <View style={styles.resultRow}>
              <Text style={styles.resultLabel}>Nuevo</Text>
              <Text style={styles.resultValueStrong}>{scopeShortLabel(appliedResult.new_scope)}</Text>
            </View>
            <View style={styles.resultRow}>
              <Text style={styles.resultLabel}>Aplicado</Text>
              <Text style={styles.resultValue}>
                {new Date(appliedResult.applied_at).toLocaleString()}
              </Text>
            </View>
            {appliedResult.forced ? (
              <View style={styles.forcedBadge}>
                <Icon name="zap" size={12} color={colorScales.amber[700]} />
                <Text style={styles.forcedBadgeText}>Aplicado con force=true</Text>
              </View>
            ) : null}
          </View>
        </View>
      );
    }
    return null;
  };

  // ---------- footer ----------
  const renderFooter = () => {
    const isLoading = previewMutation.isPending || applyMutation.isPending;

    if (step === 1) {
      return (
        <View style={styles.modalActions}>
          <Pressable
            style={[styles.modalBtn, styles.modalBtnSecondary]}
            onPress={handleClose}
            disabled={isLoading}
          >
            <Text style={styles.modalBtnSecondaryText}>Cancelar</Text>
          </Pressable>
          <Pressable
            style={[
              styles.modalBtn,
              styles.modalBtnPrimary,
              isLoading && styles.modalBtnDisabled,
            ]}
            onPress={goToPreview}
            disabled={isLoading}
          >
            {previewMutation.isPending ? (
              <ActivityIndicator size="small" color="#fff" />
            ) : (
              <Text style={styles.modalBtnPrimaryText}>Vista previa</Text>
            )}
          </Pressable>
        </View>
      );
    }

    if (step === 2) {
      const showForceBtn = canShowForceOption;
      return (
        <View style={styles.modalActions}>
          <Pressable
            style={[styles.modalBtn, styles.modalBtnSecondary]}
            onPress={() => setStep(1)}
            disabled={isLoading}
          >
            <Text style={styles.modalBtnSecondaryText}>Atrás</Text>
          </Pressable>
          {showForceBtn ? (
            <Pressable
              style={[styles.modalBtn, styles.modalBtnDanger]}
              onPress={goToForceConfirm}
              disabled={isLoading}
            >
              <Text style={styles.modalBtnDangerText}>Forzar cambio</Text>
            </Pressable>
          ) : (
            <Pressable
              style={[
                styles.modalBtn,
                styles.modalBtnPrimary,
                (!canApply || isLoading) && styles.modalBtnDisabled,
              ]}
              onPress={applyStandard}
              disabled={!canApply || isLoading}
            >
              {applyMutation.isPending ? (
                <ActivityIndicator size="small" color="#fff" />
              ) : (
                <Text style={styles.modalBtnPrimaryText}>Aplicar cambio</Text>
              )}
            </Pressable>
          )}
        </View>
      );
    }

    if (step === 3) {
      return (
        <View style={styles.modalActions}>
          <Pressable
            style={[styles.modalBtn, styles.modalBtnSecondary]}
            onPress={() => setStep(2)}
            disabled={isLoading}
          >
            <Text style={styles.modalBtnSecondaryText}>Atrás</Text>
          </Pressable>
          <Pressable
            style={[
              styles.modalBtn,
              styles.modalBtnDanger,
              (!canForceApply || isLoading) && styles.modalBtnDisabled,
            ]}
            onPress={forceApply}
            disabled={!canForceApply || isLoading}
          >
            {applyMutation.isPending ? (
              <ActivityIndicator size="small" color="#fff" />
            ) : (
              <Text style={styles.modalBtnDangerText}>Confirmar forzado</Text>
            )}
          </Pressable>
        </View>
      );
    }

    // step 4
    return (
      <View style={styles.modalActions}>
        <Pressable
          style={[styles.modalBtn, styles.modalBtnPrimary, { flex: 1 }]}
          onPress={handleClose}
        >
          <Text style={styles.modalBtnPrimaryText}>Cerrar</Text>
        </Pressable>
      </View>
    );
  };

  return (
    <OrgCenteredModal
      visible={visible}
      onClose={handleClose}
      title="Cambiar modo operativo"
      subtitle={renderStepLabel()}
      size="md"
      footer={renderFooter()}
    >
      <ScrollView showsVerticalScrollIndicator={false}>
        {renderStepDots()}
        {step === 1 && renderStep1()}
        {step === 2 && renderStep2()}
        {step === 3 && renderStep3()}
        {step === 4 && renderStep4()}
      </ScrollView>
    </OrgCenteredModal>
  );
}

// ----------------------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------------------

function extractErrorMessage(err: any, fallback: string): string {
  const payload = err?.error ?? err?.response?.data;
  if (payload) {
    const msg = payload?.message;
    if (Array.isArray(msg)) {
      const joined = msg.filter(Boolean).map(String).join('. ');
      if (joined) return joined;
    }
    if (typeof msg === 'string' && msg.trim()) return msg;
    if (
      typeof payload?.error === 'string' &&
      !['Bad Request', 'Forbidden', 'Conflict', 'Internal Server Error'].includes(payload.error)
    ) {
      return payload.error;
    }
  }

  const status = err?.status ?? err?.response?.status;
  if (status === 0 || status === undefined) {
    return 'No se pudo conectar con el servidor. Revisa tu conexión.';
  }
  if (status === 401) {
    return 'No tienes permisos para esta acción. Cierra sesión y vuelve a iniciar.';
  }
  if (status === 403) {
    return 'Esta organización es partner de Vendix y no puede cambiar el modo operativo.';
  }
  if (status === 409) {
    const blockers = payload?.blockers;
    if (Array.isArray(blockers) && blockers.length) {
      return `No se pudo aplicar el cambio: ${blockers
        .map((b: any) => b?.message || b?.code)
        .filter(Boolean)
        .join(' • ')}`;
    }
    return 'Hay condiciones que bloquean el cambio operativo.';
  }
  if (status >= 500) {
    return 'Error en el servidor al aplicar el cambio. Intenta de nuevo.';
  }
  return fallback;
}

// ----------------------------------------------------------------------------
// Styles
// ----------------------------------------------------------------------------

const styles = StyleSheet.create({
  // step indicator
  stepDotsRow: {
    flexDirection: 'row',
    gap: spacing[2],
    marginBottom: spacing[4],
    justifyContent: 'center',
  },
  stepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colorScales.gray[200],
  },
  stepDotActive: { backgroundColor: colors.primary, width: 24 },
  stepDotPast: { backgroundColor: colors.primary },

  // body
  bodyText: {
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[700],
    lineHeight: typography.lineHeight.normal * typography.fontSize.sm,
    marginBottom: spacing[4],
  },

  // summary card (step 1)
  summaryCard: {
    backgroundColor: colorScales.gray[50],
    borderRadius: borderRadius.lg,
    padding: spacing[4],
    marginBottom: spacing[4],
    borderWidth: 1,
    borderColor: colorScales.gray[100],
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing[2],
  },
  summaryLabel: {
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[500],
  },
  summaryValueWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  summaryValue: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    color: colorScales.gray[700],
  },
  summaryValueStrong: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    color: colors.primary,
  },
  summaryArrow: {
    alignItems: 'center',
    paddingVertical: spacing[1],
  },

  // form
  label: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colorScales.gray[700],
    marginBottom: spacing[2],
  },
  labelRequired: {
    color: colorScales.red[600],
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.normal,
  },
  textarea: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colorScales.gray[200],
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    minHeight: 80,
    textAlignVertical: 'top',
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[900],
    marginBottom: spacing[2],
  },
  charCounter: {
    fontSize: typography.fontSize.xs,
    color: colorScales.green[600],
    marginBottom: spacing[3],
    textAlign: 'right',
  },
  charCounterWarn: {
    color: colorScales.amber[600],
  },

  // preview (step 2)
  previewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  previewDirection: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold,
    color: colorScales.gray[900],
  },
  directionPill: {
    paddingHorizontal: spacing[2],
    paddingVertical: 4,
    borderRadius: borderRadius.full,
  },
  directionPillUp: { backgroundColor: colorScales.green[100] },
  directionPillDown: { backgroundColor: colorScales.amber[100] },
  directionPillText: {
    fontSize: 10,
    fontWeight: typography.fontWeight.bold,
    color: colorScales.gray[700],
    letterSpacing: 0.5,
  },
  warningsBox: {
    backgroundColor: colorScales.amber[50],
    borderRadius: borderRadius.md,
    padding: spacing[3],
    marginBottom: spacing[3],
    borderWidth: 1,
    borderColor: colorScales.amber[200],
  },
  warningsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginBottom: spacing[2],
  },
  warningsHeaderText: {
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    color: colorScales.amber[700],
    textTransform: 'uppercase',
  },
  warningText: {
    fontSize: typography.fontSize.xs,
    color: colorScales.amber[700],
    marginLeft: spacing[2],
    marginBottom: 2,
  },
  blockersBox: {
    backgroundColor: colorScales.red[50],
    borderRadius: borderRadius.md,
    padding: spacing[3],
    marginBottom: spacing[3],
    borderWidth: 1,
    borderColor: colorScales.red[200],
  },
  blockersHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginBottom: spacing[2],
  },
  blockersHeaderText: {
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    color: colorScales.red[700],
    textTransform: 'uppercase',
  },
  blockerRow: {
    paddingVertical: spacing[2],
    borderTopWidth: 1,
    borderTopColor: colorScales.red[100],
  },
  blockerTitle: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colorScales.red[800],
    marginBottom: 2,
  },
  blockerMessage: {
    fontSize: typography.fontSize.xs,
    color: colorScales.red[700],
  },
  canApplyBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    backgroundColor: colorScales.green[50],
    borderRadius: borderRadius.md,
    padding: spacing[3],
    marginBottom: spacing[3],
    borderWidth: 1,
    borderColor: colorScales.green[200],
  },
  canApplyText: {
    fontSize: typography.fontSize.sm,
    color: colorScales.green[700],
    flex: 1,
  },

  // force-confirm (step 3)
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing[2],
    backgroundColor: colorScales.amber[50],
    borderRadius: borderRadius.md,
    padding: spacing[3],
    marginBottom: spacing[4],
    borderWidth: 1,
    borderColor: colorScales.amber[200],
  },
  warningBannerText: {
    flex: 1,
    fontSize: typography.fontSize.sm,
    color: colorScales.amber[700],
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    marginBottom: spacing[4],
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: colorScales.gray[300],
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxLabel: {
    flex: 1,
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[700],
  },

  // result (step 4)
  resultErrorBox: {
    alignItems: 'center',
    paddingVertical: spacing[4],
  },
  resultErrorTitle: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold,
    color: colorScales.red[700],
    marginTop: spacing[2],
  },
  resultErrorMessage: {
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[600],
    textAlign: 'center',
    marginTop: spacing[2],
  },
  resultSuccessBox: {
    alignItems: 'center',
    paddingVertical: spacing[2],
  },
  resultSuccessTitle: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold,
    color: colorScales.green[700],
    marginTop: spacing[2],
    marginBottom: spacing[4],
  },
  resultSummary: {
    width: '100%',
    backgroundColor: colorScales.gray[50],
    borderRadius: borderRadius.lg,
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colorScales.gray[100],
  },
  resultRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: spacing[2],
  },
  resultLabel: {
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[500],
  },
  resultValue: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    color: colorScales.gray[700],
  },
  resultValueStrong: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    color: colors.primary,
  },
  forcedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    alignSelf: 'center',
    marginTop: spacing[3],
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
    backgroundColor: colorScales.amber[50],
    borderRadius: borderRadius.full,
  },
  forcedBadgeText: {
    fontSize: typography.fontSize.xs,
    color: colorScales.amber[700],
    fontWeight: typography.fontWeight.semibold,
  },

  // errors
  errorBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing[2],
    backgroundColor: colorScales.red[50],
    borderRadius: borderRadius.md,
    padding: spacing[3],
    marginTop: spacing[2],
    borderWidth: 1,
    borderColor: colorScales.red[200],
  },
  errorText: {
    flex: 1,
    fontSize: typography.fontSize.xs,
    color: colorScales.red[700],
  },

  // footer buttons
  modalActions: {
    flexDirection: 'row',
    gap: spacing[2],
    justifyContent: 'flex-end',
  },
  modalBtn: {
    height: 40,
    paddingHorizontal: spacing[4],
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
  },
  modalBtnSecondary: { backgroundColor: colorScales.gray[100] },
  modalBtnSecondaryText: {
    color: colorScales.gray[700],
    fontWeight: typography.fontWeight.semibold,
  },
  modalBtnPrimary: { backgroundColor: colors.primary },
  modalBtnPrimaryText: {
    color: '#FFFFFF',
    fontWeight: typography.fontWeight.semibold,
  },
  modalBtnDanger: { backgroundColor: colorScales.red[600] },
  modalBtnDangerText: {
    color: '#FFFFFF',
    fontWeight: typography.fontWeight.semibold,
  },
  modalBtnDisabled: { opacity: 0.6 },
});

// apps/frontend/src/app/private/modules/organization/settings/operating-scope/components/change-scope-wizard.component.ts
import {
  Component,
  DestroyRef,
  computed,
  inject,
  input,
  model,
  output,
  signal,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { HttpErrorResponse } from '@angular/common/http';
import { RouterLink } from '@angular/router';

import {
  AlertBannerComponent,
  ButtonComponent,
  IconComponent,
  ModalComponent,
  SpinnerComponent,
  TextareaComponent,
} from '../../../../../../shared/components';
import { AuthFacade } from '../../../../../../core/store/auth/auth.facade';
import {
  OperatingScopeApplyResult,
  OperatingScopeBlocker,
  OperatingScopePreview,
  OperatingScopeValue,
  OperatingScopeWizardService,
} from '../services/operating-scope.service';

/**
 * Wizard steps:
 *   1 — Confirm intent (current vs target + optional reason).
 *   2 — Preview (server-authoritative blockers + warnings).
 *   3 — Force-confirm (only when downgrade has blockers and the user opts to
 *       force-apply; double confirmation + mandatory reason ≥10 chars).
 *   4 — Result (success or error after `/apply`).
 */
type WizardStep = 1 | 2 | 3 | 4;

const FORCE_REASON_MIN_LENGTH = 10;

@Component({
  selector: 'app-change-scope-wizard',
  standalone: true,
  imports: [
    AlertBannerComponent,
    ButtonComponent,
    IconComponent,
    ModalComponent,
    RouterLink,
    SpinnerComponent,
    TextareaComponent,
  ],
  templateUrl: './change-scope-wizard.component.html',
  styleUrl: './change-scope-wizard.component.scss',
})
export class ChangeScopeWizardComponent {
  private readonly service = inject(OperatingScopeWizardService);
  private readonly authFacade = inject(AuthFacade);
  private readonly destroyRef = inject(DestroyRef);

  // ---------- inputs / outputs ----------
  readonly isOpen = model<boolean>(false);
  readonly currentScope = input.required<OperatingScopeValue>();
  readonly targetScope = input.required<OperatingScopeValue>();
  readonly applied = output<OperatingScopeApplyResult>();

  // ---------- local state ----------
  readonly step = signal<WizardStep>(1);
  readonly reason = signal<string>('');
  readonly forceReason = signal<string>('');
  readonly understandsConsequences = signal<boolean>(false);

  readonly previewLoading = signal(false);
  readonly previewError = signal<string | null>(null);
  readonly preview = signal<OperatingScopePreview | null>(null);

  readonly applyLoading = signal(false);
  readonly applyError = signal<string | null>(null);
  readonly applyResult = signal<OperatingScopeApplyResult | null>(null);

  // ---------- computed ----------
  readonly directionLabel = computed(() => {
    const from = this.currentScope();
    const to = this.targetScope();
    return `${this.scopeLabel(from)} → ${this.scopeLabel(to)}`;
  });

  /** Direction reported by the preview. UP and DOWN drive different UX. */
  readonly direction = computed(() => this.preview()?.direction ?? 'NOOP');

  /** Whether the user has the underlying write permission. Frontend gate
   *  only — backend re-checks `organization:settings:operating_scope:write`
   *  on the apply endpoint. */
  readonly hasWritePermission = computed(() =>
    this.authFacade.hasPermission(
      'organization:settings:operating_scope:write',
    ),
  );

  /** Force-flow is only offered when:
   *   - direction is DOWN (server ignores `force` on UP migrations),
   *   - blockers come from the server,
   *   - none of the blockers are PARTNER_LOCKED (security rail — never
   *     bypassable),
   *   - the user has the write permission. */
  readonly canShowForceOption = computed(() => {
    const p = this.preview();
    if (!p || p.blockers.length === 0) return false;
    if (p.direction !== 'DOWN') return false;
    if (p.blockers.some((b) => b.code === 'PARTNER_LOCKED')) return false;
    return this.hasWritePermission();
  });

  /** Standard apply (no force) when preview has no blockers. */
  readonly canApply = computed(() => {
    const p = this.preview();
    return !!p && p.can_apply && p.blockers.length === 0;
  });

  /** Force-apply gate: requires double-confirmation checkbox + reason ≥10. */
  readonly canForceApply = computed(() => {
    if (!this.understandsConsequences()) return false;
    return this.forceReason().trim().length >= FORCE_REASON_MIN_LENGTH;
  });

  readonly forceReasonRemaining = computed(() => {
    const trimmed = this.forceReason().trim();
    return Math.max(0, FORCE_REASON_MIN_LENGTH - trimmed.length);
  });

  // ---------- lifecycle helpers ----------
  scopeLabel(value: OperatingScopeValue): string {
    return value === 'ORGANIZATION'
      ? 'Organización (consolidado)'
      : 'Por tienda';
  }

  /** Numeric step indicator (1..4) — kept stable so the dots in the header
   *  always render the same range. The force-confirm step replaces the
   *  numbered dot 3 visually, while step 4 is "Done". */
  readonly stepDots = [1, 2, 3, 4] as const;

  resetState(): void {
    this.step.set(1);
    this.reason.set('');
    this.forceReason.set('');
    this.understandsConsequences.set(false);
    this.previewLoading.set(false);
    this.previewError.set(null);
    this.preview.set(null);
    this.applyLoading.set(false);
    this.applyError.set(null);
    this.applyResult.set(null);
  }

  closeWizard(): void {
    this.isOpen.set(false);
    // Defer reset so the close animation finishes cleanly.
    setTimeout(() => this.resetState(), 250);
  }

  onReasonChange(value: string): void {
    this.reason.set(value || '');
  }

  onForceReasonChange(value: string): void {
    this.forceReason.set(value || '');
  }

  toggleUnderstandsConsequences(event: Event): void {
    const target = event.target as HTMLInputElement | null;
    this.understandsConsequences.set(target?.checked === true);
  }

  // ---------- step 1 → step 2 ----------
  goToPreview(): void {
    this.previewLoading.set(true);
    this.previewError.set(null);
    this.preview.set(null);

    this.service
      .preview(this.targetScope(), this.reason())
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (preview) => {
          this.preview.set(preview);
          this.previewLoading.set(false);
          this.step.set(2);
        },
        error: (err: HttpErrorResponse) => {
          this.previewLoading.set(false);
          this.previewError.set(this.businessMessageFor(err));
        },
      });
  }

  // ---------- step 2 → apply (no blockers) ----------
  applyChange(): void {
    if (!this.canApply()) return;
    this.runApply(false);
  }

  // ---------- step 2 → step 3 (force flow opt-in) ----------
  goToForceConfirm(): void {
    if (!this.canShowForceOption()) return;
    this.applyError.set(null);
    this.understandsConsequences.set(false);
    this.forceReason.set('');
    this.step.set(3);
  }

  // ---------- step 3 → apply (force=true) ----------
  forceApplyChange(): void {
    if (!this.canForceApply()) return;
    this.runApply(true);
  }

  // ---------- helpers ----------
  goBackToStep1(): void {
    this.step.set(1);
    this.previewError.set(null);
  }

  goBackToPreview(): void {
    this.applyError.set(null);
    this.step.set(2);
  }

  /**
   * Friendly remediation label. Falls back to the explicit count when the
   * backend exposes one in `details.count`.
   */
  blockerCount(b: OperatingScopeBlocker): number | null {
    const c = b.details?.count;
    if (typeof c === 'number' && Number.isFinite(c)) return c;
    return null;
  }

  blockerRemediationLink(b: OperatingScopeBlocker): string | null {
    const link = b.details?.remediation_link;
    return typeof link === 'string' && link.trim() ? link : null;
  }

  /**
   * Map blocker code → short human label for the wizard list. Mirrors the
   * server messages but stays explicit for translation later.
   */
  blockerTitle(b: OperatingScopeBlocker): string {
    switch (b.code) {
      case 'OPEN_POS_TO_CENTRAL':
        return 'Órdenes de compra abiertas hacia bodega central';
      case 'OPEN_PURCHASE_ORDERS':
        return 'Órdenes de compra consolidadas abiertas';
      case 'OPEN_CROSS_STORE_TRANSFERS':
        return 'Transferencias inter-tienda abiertas';
      case 'STOCK_AT_CENTRAL':
        return 'Stock en bodega central';
      case 'ACTIVE_RESERVATIONS_AT_CENTRAL':
        return 'Reservas activas en bodega central';
      case 'PARTNER_LOCKED':
        return 'Organización partner bloqueada';
      case 'NOT_ENOUGH_STORES':
        return 'Tiendas activas insuficientes';
      case 'NO_ACTIVE_STORES':
        return 'No hay tiendas activas';
      default:
        return b.code;
    }
  }

  // ---------- private ----------
  private runApply(force: boolean): void {
    this.applyLoading.set(true);
    this.applyError.set(null);
    this.applyResult.set(null);

    // Force-apply uses the dedicated forceReason; non-forced uses the
    // optional informational reason captured on step 1.
    const reasonToSend = force ? this.forceReason().trim() : this.reason();

    this.service
      .apply(this.targetScope(), reasonToSend, force)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (result) => {
          this.applyLoading.set(false);
          this.applyResult.set(result);
          this.step.set(4);
          this.applied.emit(result);
        },
        error: (err: HttpErrorResponse) => {
          this.applyLoading.set(false);
          this.applyError.set(this.businessMessageFor(err));

          // 409 with fresh blockers means the server-side state changed
          // (e.g. another user closed/created a PO). Refresh the preview
          // so the user can re-evaluate before retrying.
          if (err?.status === 409 && Array.isArray(err?.error?.blockers)) {
            const refreshed: OperatingScopePreview | null = this.preview()
              ? {
                  ...this.preview()!,
                  blockers: err.error.blockers,
                  can_apply: false,
                }
              : null;
            if (refreshed) this.preview.set(refreshed);
            this.step.set(2);
          }
        },
      });
  }

  private extractMessage(err: HttpErrorResponse, fallback: string): string {
    if (!err) return fallback;
    const payload: any = err.error;
    if (typeof payload === 'string' && payload.trim()) return payload;
    const msg = payload?.message;
    if (Array.isArray(msg)) {
      const joined = msg.filter(Boolean).map((m) => String(m)).join('. ');
      if (joined) return joined;
    }
    if (typeof msg === 'string' && msg.trim()) return msg;
    if (
      typeof payload?.error === 'string' &&
      payload.error.trim() &&
      !['Bad Request', 'Forbidden', 'Conflict', 'Internal Server Error'].includes(
        payload.error,
      )
    ) {
      return payload.error;
    }
    if (err.statusText && err.statusText !== 'OK') return err.statusText;
    return err.message || fallback;
  }

  private businessMessageFor(err: HttpErrorResponse): string {
    const status = err?.status;
    const code: string | undefined = err?.error?.error_code;

    if (status === 0 || status === undefined) {
      return 'No se pudo conectar con el servidor. Revisa tu conexión.';
    }

    // Permission denied. Frequent cause: the user is on an old token that
    // does not yet carry the operating_scope permissions seeded later.
    if (code === 'AUTH_PERM_001' || status === 401) {
      return 'No tienes permisos para esta acción. Si los permisos se actualizaron recientemente, cierra sesión y vuelve a iniciar para refrescarlos.';
    }

    if (status === 403) {
      const partnerHint =
        'Esta organización es partner de Vendix y no puede cambiar el modo operativo.';
      const msg = this.extractMessage(err, partnerHint);
      return /partner/i.test(msg) ? msg : partnerHint;
    }

    if (status === 409) {
      const blockers = err?.error?.blockers as
        | Array<{ message: string; code?: string }>
        | undefined;
      if (blockers?.length) {
        return `No se pudo aplicar el cambio: ${blockers
          .map((b) => b.message || b.code)
          .filter(Boolean)
          .join(' • ')}`;
      }
      return this.extractMessage(
        err,
        'Hay condiciones que bloquean el cambio operativo.',
      );
    }

    if (status === 400) {
      return this.extractMessage(err, 'Datos inválidos para el cambio.');
    }

    if (status >= 500) {
      return 'Error en el servidor al aplicar el cambio. Intenta de nuevo o contacta soporte.';
    }

    return this.extractMessage(err, 'No se pudo aplicar el cambio operativo.');
  }
}

<app-modal
  [(isOpen)]="isOpen"
  title="Cambiar modo operativo"
  [subtitle]="directionLabel()"
  size="md"
  [closeOnBackdrop]="false"
  (cancel)="closeWizard()"
>
  <!-- Steps indicator -->
  <div class="mb-4 flex items-center gap-2 text-xs">
    @for (s of stepDots; track s) {
      <div class="flex items-center gap-2">
        <span
          class="flex h-6 w-6 items-center justify-center rounded-full font-semibold"
          [class.bg-primary]="step() >= s"
          [class.text-white]="step() >= s"
          [class.bg-gray-200]="step() < s"
          [class.text-gray-500]="step() < s"
          [style.background-color]="step() >= s ? 'var(--color-primary)' : ''"
        >
          {{ s }}
        </span>
        @if (s < 4) {
          <span
            class="h-0.5 w-8"
            [style.background-color]="step() > s ? 'var(--color-primary)' : 'var(--color-border)'"
          ></span>
        }
      </div>
    }
  </div>

  <!-- ---------- STEP 1 — Confirm intent ---------- -->
  @if (step() === 1) {
    <div class="space-y-4">
      <p class="text-sm text-[var(--color-text-secondary)]">
        Vas a cambiar el modo operativo de la organización. Este cambio modifica
        cómo se consultan, agregan y consolidan los datos en inventario,
        contabilidad, compras y reportes.
      </p>

      <div
        class="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-4"
      >
        <div class="grid grid-cols-2 gap-4 text-sm">
          <div>
            <p class="text-xs uppercase tracking-wider text-gray-400">Actual</p>
            <p class="mt-1 font-semibold">{{ scopeLabel(currentScope()) }}</p>
          </div>
          <div>
            <p class="text-xs uppercase tracking-wider text-gray-400">Destino</p>
            <p class="mt-1 font-semibold text-primary">
              {{ scopeLabel(targetScope()) }}
            </p>
          </div>
        </div>
      </div>

      <app-textarea
        label="Razón del cambio (opcional)"
        placeholder="Ej: la organización pasa a operar de forma consolidada por requisitos contables."
        [rows]="3"
        (valueChange)="onReasonChange($event)"
      ></app-textarea>

      @if (previewError()) {
        <app-alert-banner variant="danger" icon="alert-circle">
          {{ previewError() }}
        </app-alert-banner>
      }
    </div>
  }

  <!-- ---------- STEP 2 — Preview blockers/warnings ---------- -->
  @if (step() === 2) {
    @if (previewLoading()) {
      <div class="flex justify-center py-12">
        <app-spinner size="lg" text="Validando..."></app-spinner>
      </div>
    } @else if (preview(); as p) {
      <div class="space-y-4">
        <p class="text-sm text-[var(--color-text-secondary)]">
          Resultado de la validación previa al cambio
          <span class="font-semibold">{{ directionLabel() }}</span>.
        </p>

        @if (p.blockers.length > 0) {
          <div class="space-y-2">
            <h4 class="text-sm font-semibold text-red-700">
              Bloqueadores ({{ p.blockers.length }})
            </h4>
            @for (b of p.blockers; track b.code) {
              <div
                class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"
              >
                <div class="flex items-start gap-2">
                  <app-icon name="alert-circle" [size]="16" class="mt-0.5"></app-icon>
                  <div class="flex-1 min-w-0">
                    <div class="flex flex-wrap items-center gap-2">
                      <p class="font-semibold">{{ blockerTitle(b) }}</p>
                      @if (blockerCount(b); as count) {
                        <span
                          class="rounded-full bg-red-100 px-2 py-0.5 text-xs font-semibold text-red-700"
                        >
                          {{ count }}
                        </span>
                      }
                    </div>
                    <p class="mt-0.5">{{ b.message }}</p>
                    @if (blockerRemediationLink(b); as link) {
                      <a
                        [routerLink]="link"
                        (click)="closeWizard()"
                        class="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-red-700 underline hover:text-red-900"
                      >
                        Resolver
                        <app-icon name="arrow-right" [size]="12"></app-icon>
                      </a>
                    }
                  </div>
                </div>
              </div>
            }
          </div>
        }

        @if (p.warnings.length > 0) {
          <div class="space-y-2">
            <h4 class="text-sm font-semibold text-yellow-700">
              Advertencias ({{ p.warnings.length }})
            </h4>
            @for (w of p.warnings; track w) {
              <div
                class="rounded-lg border border-yellow-200 bg-yellow-50 p-3 text-sm text-yellow-800"
              >
                <div class="flex items-start gap-2">
                  <app-icon name="alert-triangle" [size]="16" class="mt-0.5"></app-icon>
                  <p>{{ w }}</p>
                </div>
              </div>
            }
          </div>
        }

        @if (p.blockers.length === 0 && p.warnings.length === 0) {
          <app-alert-banner variant="success" icon="check-circle">
            La organización está lista para aplicar el cambio sin restricciones.
          </app-alert-banner>
        }

        @if (canShowForceOption()) {
          <app-alert-banner variant="warning" icon="alert-triangle">
            <span class="font-semibold">¿No puedes resolver los bloqueadores?</span>
            Puedes forzar el downgrade para ignorarlos. Esta acción queda
            registrada en el historial de auditoría con tu usuario y razón.
          </app-alert-banner>
        }

        @if (applyError()) {
          <app-alert-banner variant="danger" icon="alert-circle">
            {{ applyError() }}
          </app-alert-banner>
        }
      </div>
    }
  }

  <!-- ---------- STEP 3 — Force confirmation ---------- -->
  @if (step() === 3) {
    @if (preview(); as p) {
      <div class="space-y-4">
        <app-alert-banner variant="danger" icon="alert-triangle">
          <span class="font-semibold">Vas a forzar el downgrade.</span>
          Los siguientes bloqueadores serán ignorados. Asegúrate de entender las
          consecuencias antes de continuar.
        </app-alert-banner>

        <div class="space-y-2">
          <h4 class="text-sm font-semibold text-red-700">
            Bloqueadores que serán ignorados ({{ p.blockers.length }})
          </h4>
          @for (b of p.blockers; track b.code) {
            <div
              class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"
            >
              <div class="flex items-start gap-2">
                <app-icon name="alert-circle" [size]="16" class="mt-0.5"></app-icon>
                <div class="flex-1 min-w-0">
                  <div class="flex flex-wrap items-center gap-2">
                    <p class="font-semibold">{{ blockerTitle(b) }}</p>
                    @if (blockerCount(b); as count) {
                      <span
                        class="rounded-full bg-red-100 px-2 py-0.5 text-xs font-semibold text-red-700"
                      >
                        {{ count }}
                      </span>
                    }
                  </div>
                  <p class="mt-0.5">{{ b.message }}</p>
                </div>
              </div>
            </div>
          }
        </div>

        <label
          class="flex cursor-pointer items-start gap-3 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-3 text-sm"
        >
          <input
            type="checkbox"
            class="mt-0.5 h-4 w-4 cursor-pointer accent-[var(--color-primary)]"
            [checked]="understandsConsequences()"
            (change)="toggleUnderstandsConsequences($event)"
          />
          <span>
            <span class="font-semibold">Entiendo las consecuencias.</span>
            <span class="ml-1 text-[var(--color-text-secondary)]">
              El stock, las órdenes y reservas en bodega central podrían quedar
              inaccesibles desde scope STORE. La acción quedará registrada en
              auditoría.
            </span>
          </span>
        </label>

        <app-textarea
          label="Razón del force (obligatorio, mínimo 10 caracteres)"
          placeholder="Ej: cierre operativo de bodega central; las reservas se liberarán manualmente."
          [rows]="3"
          [required]="true"
          (valueChange)="onForceReasonChange($event)"
        ></app-textarea>

        @if (forceReasonRemaining() > 0) {
          <p class="text-xs text-[var(--color-text-secondary)]">
            Faltan {{ forceReasonRemaining() }} caracteres para alcanzar el
            mínimo requerido.
          </p>
        }

        @if (applyError()) {
          <app-alert-banner variant="danger" icon="alert-circle">
            {{ applyError() }}
          </app-alert-banner>
        }
      </div>
    }
  }

  <!-- ---------- STEP 4 — Result ---------- -->
  @if (step() === 4) {
    @if (applyResult(); as r) {
      <div class="space-y-4 py-4">
        <div class="flex flex-col items-center gap-3 text-center">
          <div
            class="rounded-full p-3"
            [class.bg-green-100]="!r.forced"
            [class.text-green-600]="!r.forced"
            [class.bg-yellow-100]="r.forced"
            [class.text-yellow-600]="r.forced"
          >
            <app-icon
              [name]="r.forced ? 'alert-triangle' : 'check-circle'"
              [size]="32"
            ></app-icon>
          </div>
          <h3 class="text-lg font-semibold text-[var(--color-text-primary)]">
            @if (r.forced) {
              Modo operativo forzado
            } @else {
              Modo operativo actualizado
            }
          </h3>
          <p class="text-sm text-[var(--color-text-secondary)]">
            La organización ahora opera como
            <span class="font-semibold">{{ scopeLabel(r.new_scope) }}</span>.
            @if (r.forced) {
              <br />
              <span class="text-yellow-700">
                Se ignoraron bloqueadores. Revisa el historial de auditoría.
              </span>
            }
          </p>
        </div>

        <div
          class="rounded-lg bg-[var(--color-surface)] p-3 text-xs text-[var(--color-text-secondary)]"
        >
          <p>
            Anterior: <strong>{{ scopeLabel(r.previous_scope) }}</strong>
          </p>
          <p>
            Audit log ID: <strong>#{{ r.audit_log_id }}</strong>
          </p>
          @if (r.forced) {
            <p class="mt-1 text-yellow-700">
              <strong>Forzado:</strong> sí (registrado en audit_logs)
            </p>
          }
        </div>
      </div>
    }
  }

  <!-- ---------- FOOTER ---------- -->
  <div slot="footer" class="flex flex-wrap justify-end gap-2">
    @if (step() === 1) {
      <app-button variant="ghost" (click)="closeWizard()">Cancelar</app-button>
      <app-button
        variant="primary"
        [loading]="previewLoading()"
        (click)="goToPreview()"
        >Continuar</app-button
      >
    }
    @if (step() === 2) {
      <app-button
        variant="ghost"
        [disabled]="applyLoading()"
        (click)="goBackToStep1()"
        >Atrás</app-button
      >
      @if (canShowForceOption()) {
        <app-button
          variant="outline-warning"
          [disabled]="applyLoading()"
          (click)="goToForceConfirm()"
          >Forzar downgrade</app-button
        >
      }
      <app-button
        variant="primary"
        [disabled]="!canApply()"
        [loading]="applyLoading()"
        (click)="applyChange()"
        >Aplicar cambio</app-button
      >
    }
    @if (step() === 3) {
      <app-button
        variant="ghost"
        [disabled]="applyLoading()"
        (click)="goBackToPreview()"
        >Cancelar</app-button
      >
      <app-button
        variant="danger"
        [disabled]="!canForceApply()"
        [loading]="applyLoading()"
        (click)="forceApplyChange()"
        >Force downgrade</app-button
      >
    }
    @if (step() === 4) {
      <app-button variant="primary" (click)="closeWizard()">Cerrar</app-button>
    }
  </div>
</app-modal>
