// apps/mobile/src/shared/components/badge/badge.tsx
import { View, Text, type ViewProps } from 'react-native';

type BadgeVariant = 'default' | 'success' | 'warning' | 'error' | 'info';
type BadgeSize = 'sm' | 'md';

interface BadgeProps extends ViewProps {
  label: string;
  variant?: BadgeVariant;
  size?: BadgeSize;
}

const variantClasses: Record<BadgeVariant, string> = {
  default: 'bg-gray-100 text-gray-700',
  success: 'bg-green-100 text-green-700',
  warning: 'bg-amber-100 text-amber-700',
  error: 'bg-red-100 text-red-700',
  info: 'bg-blue-100 text-blue-700',
};

const sizeClasses: Record<BadgeSize, string> = {
  sm: 'px-2 py-0.5 text-xs',
  md: 'px-2.5 py-1 text-sm',
};

export function Badge({
  label,
  variant = 'default',
  size = 'md',
  className = '',
  ...props
}: BadgeProps) {
  return (
    <View
      className={`
        inline-flex items-center justify-center rounded-full font-medium
        ${variantClasses[variant]}
        ${sizeClasses[size]}
        ${className}
      `}
      {...props}
    >
      <Text className={size === 'sm' ? 'text-xs' : 'text-sm'}>{label}</Text>
    </View>
  );
}

// apps/frontend/src/app/shared/components/badge/badge.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export type BadgeVariant =
  | 'success'
  | 'neutral'
  | 'error'
  | 'primary'
  | 'warning';

export type BadgeSize = 'xsm' | 'sm' | 'md';

@Component({
  selector: 'app-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span
      class="inline-flex items-center rounded-full font-medium"
      [ngClass]="[sizeClasses, variantClasses]"
    >
      <ng-content></ng-content>
    </span>
  `,
})
export class BadgeComponent {
  @Input() variant: BadgeVariant = 'neutral';
  @Input() size: BadgeSize = 'sm';

  get sizeClasses(): string {
    const sizes = {
      xsm: 'px-1.5 py-0.5 text-[10px]',
      sm: 'px-2.5 py-0.5 text-xs',
      md: 'px-3 py-1 text-sm',
    };
    return sizes[this.size];
  }

  get variantClasses(): string {
    const variants = {
      success: 'bg-green-100 text-green-800',
      neutral: 'bg-gray-100 text-gray-800',
      error: 'bg-red-100 text-red-800',
      primary: 'bg-blue-100 text-blue-800',
      warning: 'bg-yellow-100 text-yellow-800',
    };
    return variants[this.variant];
  }
}
