// apps/frontend/src/app/private/modules/store/pos/components/pos-mobile-footer.component.ts
import {
  Component,
  input,
  output,
  inject,
} from '@angular/core';

import { IconComponent } from '../../../../../shared/components/icon/icon.component';
import { CartSummary } from '../models/cart.model';
import { CurrencyFormatService } from '../../../../../shared/pipes/currency';

@Component({
  selector: 'app-pos-mobile-footer',
  standalone: true,
  imports: [IconComponent],
  template: `
    <div class="pos-mobile-footer">
      <!-- Row 1: Cart Summary + View Detail Button -->
      <div class="summary-row">
        <div class="cart-summary">
          <div class="cart-icon-wrapper">
            <app-icon name="shopping-cart" [size]="20"></app-icon>
            @if (itemCount() > 0) {
              <span class="cart-badge">
                {{ itemCount() > 99 ? '99+' : itemCount() }}
              </span>
            }
          </div>
          <div class="cart-totals">
            <span class="total-label">Total</span>
            <span class="total-amount">{{
              formatCurrency(cartSummary()?.total || 0)
            }}</span>
            <span class="tax-amount">
              IVA {{ formatCurrency(cartSummary()?.taxAmount || 0) }}
            </span>
          </div>
        </div>

        <button
          class="view-detail-btn"
          (click)="viewCart.emit()"
          [disabled]="itemCount() === 0"
          >
          <span>Ver detalle</span>
          <app-icon name="chevron-up" [size]="16"></app-icon>
        </button>
      </div>

      @if (isQuotationMode()) {
        <!-- Quotation mode: single button -->
        <button
          class="action-btn checkout-btn checkout-btn-full"
          (click)="quote.emit()"
          [disabled]="itemCount() === 0"
          >
          <app-icon name="file-text" [size]="18"></app-icon>
          <span>Crear Cotización</span>
        </button>
      } @else if (isLayawayMode()) {
        <!-- Layaway mode: single button -->
        <button
          class="action-btn checkout-btn checkout-btn-full"
          (click)="layaway.emit()"
          [disabled]="itemCount() === 0"
          >
          <app-icon name="calendar" [size]="18"></app-icon>
          <span>Crear Plan Separé</span>
        </button>
      } @else {
        <!-- Row 2: Secondary Action Buttons -->
        <div class="actions-row">
          <button
            class="action-btn custom-item-btn"
            (click)="customItem.emit()"
            [disabled]="!canCreateCustomItems()"
            >
            <app-icon name="file-plus" [size]="16"></app-icon>
            <span>Ítem</span>
          </button>
          <button
            class="action-btn save-btn"
            (click)="saveDraft.emit()"
            [disabled]="itemCount() === 0"
            >
            <app-icon name="save" [size]="16"></app-icon>
            <span>Guardar</span>
          </button>
          <button
            class="action-btn shipping-btn"
            (click)="shipping.emit()"
            [disabled]="itemCount() === 0"
            >
            <app-icon name="truck" [size]="16"></app-icon>
            <span>Envío</span>
          </button>
        </div>
        <!-- Row 3: Primary CTA -->
        <button
          class="action-btn checkout-btn checkout-btn-full"
          (click)="checkout.emit()"
          [disabled]="itemCount() === 0"
          >
          <app-icon name="credit-card" [size]="18"></app-icon>
          <span>Cobrar</span>
        </button>
      }
    </div>
    `,
  styles: [
    `
      :host {
        display: block;
      }

      .pos-mobile-footer {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        z-index: 40;
        background: rgba(var(--color-surface-rgb, 255, 255, 255), 0.92);
        backdrop-filter: blur(20px);
        -webkit-backdrop-filter: blur(20px);
        border-top: 1px solid var(--color-border);
        padding: 10px 12px;
        padding-bottom: calc(10px + env(safe-area-inset-bottom, 0px));
        display: flex;
        flex-direction: column;
        gap: 10px;
      }

      /* Row 1: Summary */
      .summary-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 10px;
      }

      .cart-summary {
        display: flex;
        align-items: center;
        gap: 10px;
        flex: 1;
        min-width: 0;
      }

      .cart-icon-wrapper {
        position: relative;
        flex-shrink: 0;
        width: 36px;
        height: 36px;
        background: var(--color-primary);
        border-radius: 10px;
        display: flex;
        align-items: center;
        justify-content: center;
        color: white;
      }

      .cart-badge {
        position: absolute;
        top: -5px;
        right: -5px;
        min-width: 18px;
        height: 18px;
        padding: 0 4px;
        background: var(--color-destructive, #ef4444);
        color: white;
        font-size: 10px;
        font-weight: 700;
        border-radius: 9px;
        display: flex;
        align-items: center;
        justify-content: center;
        line-height: 1;
        border: 2px solid var(--color-surface);
      }

      .cart-totals {
        display: flex;
        flex-direction: column;
        min-width: 0;
      }

      .total-label {
        font-size: 11px;
        font-weight: 500;
        color: var(--color-text-secondary);
        line-height: 1;
      }

      .total-amount {
        font-size: 18px;
        font-weight: 800;
        color: var(--color-text-primary);
        line-height: 1.2;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }

      .tax-amount {
        margin-top: 2px;
        font-size: 11px;
        font-weight: 600;
        color: var(--color-text-secondary);
        line-height: 1.1;
      }

      .view-detail-btn {
        display: flex;
        align-items: center;
        gap: 6px;
        padding: 8px 14px;
        background: var(--color-muted);
        border: 1px solid var(--color-border);
        border-radius: 20px;
        color: var(--color-text-primary);
        font-size: 13px;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.2s ease;
        flex-shrink: 0;
        white-space: nowrap;
      }

      .view-detail-btn:hover:not(:disabled) {
        background: var(--color-primary-light);
        border-color: var(--color-primary);
        color: var(--color-primary);
      }

      .view-detail-btn:active:not(:disabled) {
        transform: scale(0.97);
      }

      .view-detail-btn:disabled {
        opacity: 0.4;
        cursor: not-allowed;
      }

      /* Row 2: Actions */
      .actions-row {
        display: grid;
        grid-template-columns: repeat(3, minmax(0, 1fr));
        gap: 10px;
      }

      .action-btn {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 8px;
        height: 38px;
        border: none;
        border-radius: 12px;
        font-size: 13px;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.2s ease;
      }

      .checkout-btn-full {
        width: 100%;
        height: 46px;
        font-size: 15px;
        font-weight: 700;
        box-shadow: 0 4px 12px rgba(var(--color-primary-rgb), 0.3);
      }

      .action-btn:active:not(:disabled) {
        transform: scale(0.97);
      }

      .action-btn:disabled {
        opacity: 0.4;
        cursor: not-allowed;
      }

      .save-btn {
        background: var(--color-surface);
        border: 1px solid var(--color-border);
        color: var(--color-text-primary);
      }

      .custom-item-btn {
        background: rgba(var(--color-primary-rgb), 0.08);
        border: 1px solid rgba(var(--color-primary-rgb), 0.24);
        color: var(--color-primary);
      }

      .custom-item-btn:hover:not(:disabled) {
        background: rgba(var(--color-primary-rgb), 0.14);
      }

      .save-btn:hover:not(:disabled) {
        background: var(--color-muted);
        border-color: var(--color-text-secondary);
      }

      .shipping-btn {
        background: var(--color-surface);
        border: 1px solid rgba(var(--color-primary-rgb), 0.5);
        color: var(--color-primary);
      }

      .shipping-btn:hover:not(:disabled) {
        background: rgba(var(--color-primary-rgb), 0.05);
      }

      .checkout-btn {
        background: var(--color-primary);
        color: white;
      }

      .checkout-btn:hover:not(:disabled) {
        filter: brightness(1.1);
      }

      /* Tablet: Sync with sidebar width */
      @media (min-width: 768px) and (max-width: 1023px) {
        .pos-mobile-footer {
          left: var(
            --sidebar-width-current,
            var(--sidebar-width-collapsed, 4rem)
          );
        }
      }

      /* iPad and larger - hide this footer */
      @media (min-width: 1024px) {
        .pos-mobile-footer {
          display: none;
        }
      }

      /* Extra small screens */
      @media (max-width: 340px) {
        .total-amount {
          font-size: 16px;
        }

        .view-detail-btn {
          padding: 8px 10px;
          font-size: 12px;
        }

        .action-btn {
          font-size: 12px;
          gap: 6px;
        }
      }
    `,
  ],
})
export class PosMobileFooterComponent {
  private currencyService = inject(CurrencyFormatService);

  readonly cartSummary = input<CartSummary | null>(null);
  readonly itemCount = input<number>(0);
  readonly isTablet = input<boolean>(false);
  readonly isQuotationMode = input<boolean>(false);
  readonly isLayawayMode = input<boolean>(false);
  readonly canCreateCustomItems = input<boolean>(false);

  readonly viewCart = output<void>();
  readonly customItem = output<void>();
  readonly saveDraft = output<void>();
  readonly shipping = output<void>();
  readonly checkout = output<void>();
  readonly quote = output<void>();
  readonly layaway = output<void>();

  formatCurrency(amount: number): string {
    return this.currencyService.format(amount);
  }
}

// apps/mobile/src/features/pos/components/pos-mobile-footer.tsx
import React from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { colors, colorScales, spacing, typography, borderRadius } from '@/shared/theme';
import { Icon } from '@/shared/components/icon/icon';
import { formatCurrency } from '@/shared/utils/currency';
import type { PosMode } from '@/features/store/types';

interface PosMobileFooterProps {
  itemCount: number;
  total: number;
  taxAmount: number;
  mode: PosMode;
  onViewCart: () => void;
  onCustomItem: () => void;
  /** "Crear" — abre `pos-order-create-modal` (fulfillment + KDS guard). */
  onCreate: () => void;
  onShipping: () => void;
  /** Handler del CTA primario. Varía por modo: Cobrar / Crear cotización / Crear plan separé. */
  onPrimaryCta: () => void;
  canCreateCustomItems?: boolean;
}

// ── Mode-aware primary CTA metadata (paridad con `pos.component.ts` web) ──

interface PrimaryCtaMeta {
  label: string;
  icon: string;
  bg: string;
  shadow: string;
}

const PRIMARY_CTA_META: Record<PosMode, PrimaryCtaMeta> = {
  sale: {
    label: 'Cobrar',
    icon: 'credit-card',
    bg: colors.primary,
    shadow: colors.primary,
  },
  quotation: {
    label: 'Crear cotización',
    icon: 'file-text',
    bg: colors.primary,
    shadow: colors.primary,
  },
  layaway: {
    label: 'Crear plan separé',
    icon: 'calendar-clock',
    bg: colorScales.amber[600],
    shadow: colorScales.amber[600],
  },
};

export function PosMobileFooter({
  itemCount,
  total,
  taxAmount,
  mode,
  onViewCart,
  onCustomItem,
  onCreate,
  onShipping,
  onPrimaryCta,
  canCreateCustomItems = false,
}: PosMobileFooterProps) {
  const insets = useSafeAreaInsets();
  if (itemCount === 0) return null;

  const cta = PRIMARY_CTA_META[mode];

  return (
    <View style={[styles.footer, { paddingBottom: insets.bottom + 10 }]}>
      {/* Row 1: Cart Summary + View Detail Button */}
      <View style={styles.summaryRow}>
        <View style={styles.cartSummary}>
          <View style={styles.cartIconWrapper}>
            <Icon name="shopping-cart" size={20} color="#FFFFFF" />
            <View style={styles.cartBadge}>
              <Text style={styles.cartBadgeText}>
                {itemCount > 99 ? '99+' : itemCount}
              </Text>
            </View>
          </View>
          <View style={styles.cartTotals}>
            <Text style={styles.totalLabel}>Total</Text>
            <Text style={styles.totalAmount}>{formatCurrency(total)}</Text>
            <Text style={styles.taxAmount}>
              IVA {formatCurrency(taxAmount)}
            </Text>
          </View>
        </View>

        <Pressable
          style={styles.viewDetailBtn}
          onPress={onViewCart}
        >
          <Text style={styles.viewDetailText}>Ver detalle</Text>
          <Icon name="chevron-up" size={16} color={colorScales.gray[500]} />
        </Pressable>
      </View>

      {/* Row 2: Secondary Action Buttons — paridad web: Ítem / Crear / Envío */}
      <View style={styles.actionsRow}>
        <Pressable
          style={[styles.actionBtn, styles.customItemBtn]}
          onPress={onCustomItem}
          disabled={!canCreateCustomItems}
        >
          <Icon name="file-plus" size={16} color={colors.primary} />
          <Text style={[styles.actionText, styles.customItemText]}>Ítem</Text>
        </Pressable>

        <Pressable
          style={[styles.actionBtn, styles.createBtn]}
          onPress={onCreate}
        >
          <Icon name="plus-circle" size={16} color={colorScales.gray[700]} />
          <Text style={styles.actionText}>Crear</Text>
        </Pressable>

        <Pressable
          style={[styles.actionBtn, styles.shippingBtn]}
          onPress={onShipping}
        >
          <Icon name="truck" size={16} color={colors.primary} />
          <Text style={[styles.actionText, styles.shippingText]}>Envío</Text>
        </Pressable>
      </View>

      {/* Row 3: Primary CTA — varía por modo */}
      <Pressable
        style={[styles.checkoutBtn, { backgroundColor: cta.bg, shadowColor: cta.shadow }]}
        onPress={onPrimaryCta}
      >
        <Icon name={cta.icon} size={18} color="#FFFFFF" />
        <Text style={styles.checkoutText}>{cta.label}</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderTopWidth: 1,
    borderTopColor: colorScales.gray[200],
    padding: 10,
    paddingBottom: 20,
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  cartSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  cartIconWrapper: {
    position: 'relative',
    flexShrink: 0,
    width: 36,
    height: 36,
    backgroundColor: colors.primary,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    backgroundColor: colors.error,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: colors.background,
  },
  cartBadgeText: {
    fontSize: 10,
    fontWeight: typography.fontWeight.bold as any,
    color: '#FFFFFF',
  },
  cartTotals: {
    flexDirection: 'column',
  },
  totalLabel: {
    fontSize: 11,
    fontWeight: typography.fontWeight.medium as any,
    color: colorScales.gray[700],
  },
  totalAmount: {
    fontSize: 18,
    fontWeight: typography.fontWeight.bold as any,
    color: colorScales.gray[900],
  },
  taxAmount: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: typography.fontWeight.semibold as any,
    color: colorScales.gray[600],
  },
  viewDetailBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: colorScales.gray[100],
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colorScales.gray[200],
  },
  viewDetailText: {
    fontSize: 13,
    fontWeight: typography.fontWeight.semibold as any,
    color: colorScales.gray[700],
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
  },
  customItemBtn: {
    backgroundColor: 'rgba(34, 197, 94, 0.08)',
    borderColor: colorScales.green[200],
  },
  customItemText: {
    color: colorScales.green[700],
  },
  createBtn: {
    backgroundColor: colors.background,
    borderColor: colorScales.gray[200],
  },
  shippingBtn: {
    backgroundColor: colors.background,
    borderColor: colorScales.green[200],
  },
  shippingText: {
    color: colorScales.green[700],
  },
  actionText: {
    fontSize: 13,
    fontWeight: typography.fontWeight.semibold as any,
    color: colorScales.gray[700],
  },
  checkoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 46,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.xl,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  checkoutText: {
    fontSize: 15,
    fontWeight: typography.fontWeight.bold as any,
    color: '#FFFFFF',
  },
});
