// apps/mobile/app/(org-admin)/settings/operating-scope.tsx
import { useState } from 'react';
import {
  View,
  Text,
  Pressable,
  ScrollView,
  RefreshControl,
  StyleSheet,
} from 'react-native';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { OrgConfigService } from '@/features/org/services/org-config.service';
import { OrgPageContainer } from '@/shared/components/org-page-container';
import { OrgBadge } from '@/shared/components/org-badge';
import { Button } from '@/shared/components/button/button';
import { Card } from '@/shared/components/card/card';
import { Icon } from '@/shared/components/icon/icon';
import { Spinner } from '@/shared/components/spinner/spinner';
import { RecordCard } from '@/shared/components/record-card/record-card';
import { colors, colorScales, spacing, typography, borderRadius, shadows } from '@/shared/theme';
import {
  scopeShortLabel,
  scopeLabel,
  formatAuditDate,
} from '@/features/org/components/operating-scope-formatters';
import { ChangeScopeWizard } from './_components/change-scope-wizard';
import type {
  OperatingScopeValue,
  OperatingScopeAuditLogEntry,
  OperatingScopeApplyResult,
} from '@/core/models/org-admin/config.types';

/**
 * Modo operativo · ORG_ADMIN (paridad visual 1:1 con web).
 *
 * Espejo de `apps/frontend/.../settings/operating-scope/operating-scope.component.html`.
 *
 * Estructura:
 *   1. Sticky sub-header (título "Modo operativo" + subtítulo).
 *   2. Loading → app-spinner con texto.
 *   3. Error → alert-banner danger + botón "Reintentar".
 *   4. Current scope card — header (label + título + descripción + badge
 *      "Partner — bloqueado" si aplica) + partner alert + scope cards
 *      (STORE / ORGANIZATION) + botón "Cambiar modo operativo".
 *   5. Audit log card — header con icono history primary + lista de
 *      RecordCards (timestamp · change label · razón · usuario).
 *   6. Wizard modal 4 pasos.
 */

const SCOPE_DESCRIPTIONS: Record<OperatingScopeValue, string> = {
  STORE:
    'Cada tienda maneja sus propios proveedores, ubicaciones, inventario, compras, contabilidad y reportes operativos.',
  ORGANIZATION:
    'La organización consolida operación, valoración, contabilidad y reportes entre tiendas.',
};

const SCOPE_ICONS: Record<OperatingScopeValue, string> = {
  STORE: 'store',
  ORGANIZATION: 'building',
};

const SCOPE_ICON_BG: Record<OperatingScopeValue, string> = {
  STORE: '#eff6ff', // blue-50
  ORGANIZATION: '#faf5ff', // purple-50
};

const SCOPE_ICON_FG: Record<OperatingScopeValue, string> = {
  STORE: '#2563eb', // blue-600
  ORGANIZATION: '#9333ea', // purple-600
};

export default function OperatingScopeScreen() {
  const queryClient = useQueryClient();
  const [refreshing, setRefreshing] = useState(false);
  const [wizardOpen, setWizardOpen] = useState(false);
  const [pendingTarget, setPendingTarget] = useState<OperatingScopeValue | null>(null);

  const { data, isLoading, isFetching, refetch, error } = useQuery({
    queryKey: ['org-operating-scope'],
    queryFn: () => OrgConfigService.getOperatingScope(),
    staleTime: 30_000,
  });

  const onRefresh = async () => {
    setRefreshing(true);
    await refetch();
    setRefreshing(false);
  };

  const openWizardFor = (target: OperatingScopeValue) => {
    setPendingTarget(target);
    setWizardOpen(true);
  };

  const onApplied = (_result: OperatingScopeApplyResult) => {
    queryClient.invalidateQueries({ queryKey: ['org-operating-scope'] });
  };

  // ── Loading state (paridad con web <app-spinner text="Cargando...">) ──
  if (isLoading && !data) {
    return (
      <OrgPageContainer loading>
        {null}
      </OrgPageContainer>
    );
  }

  const current = data?.current ?? 'STORE';
  const isPartner = !!data?.is_partner;
  const editable = !!data?.editable && !isLoading && !isFetching;
  const auditLog = data?.audit_log_recent ?? [];

  const targetForWizard: OperatingScopeValue =
    pendingTarget ?? (current === 'STORE' ? 'ORGANIZATION' : 'STORE');

  const errorMessage = error ? extractErrorMessage(error) : null;

  return (
    <OrgPageContainer
      refreshing={refreshing}
      onRefresh={onRefresh}
      padding={false}
    >
      {/* ── Sticky sub-header — paridad con <app-sticky-header> web ── */}
      <View style={styles.stickySubHeader}>
        <View style={styles.titleRow}>
          <View style={styles.titleLeft}>
            <Pressable
              onPress={() => {}}
              hitSlop={8}
              style={styles.backBtn}
              accessibilityLabel="Volver"
            >
              <Icon name="arrow-left" size={16} color={colorScales.gray[500]} />
            </Pressable>

            <View style={styles.titleText}>
              <Text style={styles.title} numberOfLines={1}>
                Modo operativo
              </Text>
              <Text style={styles.subtitle} numberOfLines={2}>
                Define si la organización opera por tienda o de forma consolidada
              </Text>
            </View>
          </View>
        </View>
      </View>

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={onRefresh}
            tintColor={colors.primary}
            colors={[colors.primary]}
          />
        }
      >
        {isFetching && !data ? (
          <View style={styles.loadingBox}>
            <Spinner size="lg" />
            <Text style={styles.loadingText}>Cargando modo operativo...</Text>
          </View>
        ) : null}

        {errorMessage ? (
          <View style={styles.dangerAlert}>
            <Icon name="alert-circle" size={16} color={colorScales.red[600]} />
            <Text style={styles.dangerAlertText}>{errorMessage}</Text>
            <Pressable onPress={() => refetch()} hitSlop={6}>
              <Text style={styles.retryLink}>Reintentar</Text>
            </Pressable>
          </View>
        ) : null}

        {data ? (
          <>
            {/* ── Current scope card (paridad con <app-card>) ── */}
            <View style={styles.section}>
              <Card>
                <View style={styles.cardBody}>
                  {/* Header row: label + título + descripción (izq) + badge partner (der) */}
                  <View style={styles.currentHeaderRow}>
                    <View style={styles.currentHeaderText}>
                      <Text style={styles.eyebrow}>MODO OPERATIVO ACTUAL</Text>
                      <Text style={styles.currentTitle}>{scopeLabel(current)}</Text>
                      <Text style={styles.currentDescription}>
                        Aplica a inventario, contabilidad, compras, valoración y
                        reportes de la organización.
                      </Text>
                    </View>
                    {isPartner ? (
                      <View style={styles.partnerBadgeWrap}>
                        <OrgBadge label="Partner — bloqueado" variant="warning" />
                      </View>
                    ) : null}
                  </View>

                  {/* Partner-lock alert (paridad con <app-alert-banner warning>) */}
                  {isPartner ? (
                    <View style={styles.partnerAlert}>
                      <Icon name="lock" size={16} color={colorScales.amber[700]} />
                      <Text style={styles.partnerAlertText}>
                        Esta organización es partner de Vendix. El modo operativo
                        está fijado en <Text style={styles.partnerAlertStrong}>Por tienda</Text> y
                        no puede modificarse desde esta pantalla.
                      </Text>
                    </View>
                  ) : null}

                  {/* Scope toggle (segmented) */}
                  <View style={styles.scopeSection}>
                    <Text style={styles.eyebrow}>SELECCIONA EL MODO OPERATIVO</Text>

                    <View style={styles.scopeCardsRow}>
                      <ScopeCardButton
                        value="STORE"
                        active={current === 'STORE'}
                        disabled={!editable}
                        onPress={() => openWizardFor('STORE')}
                      />
                      <ScopeCardButton
                        value="ORGANIZATION"
                        active={current === 'ORGANIZATION'}
                        disabled={!editable}
                        onPress={() => openWizardFor('ORGANIZATION')}
                      />
                    </View>
                  </View>

                  {/* Action button — right-aligned (paridad con web flex justify-end) */}
                  <View style={styles.actions}>
                    <Button
                      title={
                        isPartner
                          ? 'Modo bloqueado (Partner)'
                          : !editable
                            ? 'Modo no editable'
                            : 'Cambiar modo operativo'
                      }
                      variant="primary"
                      onPress={() => openWizardFor(targetForWizard)}
                      disabled={isPartner || !editable}
                    />
                  </View>
                </View>
              </Card>
            </View>

            {/* ── Audit log card (paridad con <app-card> + <app-responsive-data-view>) ── */}
            <View style={styles.section}>
              <Card>
                <View style={styles.cardBody}>
                  <View style={styles.auditHeaderRow}>
                    <Icon name="history" size={18} color={colors.primary} />
                    <Text style={styles.auditHeaderTitle}>Historial reciente</Text>
                  </View>

                  {auditLog.length === 0 ? (
                    <View style={styles.emptyAudit}>
                      <Icon name="history" size={20} color={colorScales.gray[400]} />
                      <Text style={styles.emptyAuditText}>
                        Sin cambios registrados
                      </Text>
                    </View>
                  ) : (
                    <View style={styles.auditList}>
                      {auditLog.map((entry: OperatingScopeAuditLogEntry) => (
                        <View key={entry.id} style={styles.auditItem}>
                          <RecordCard
                            title={formatAuditDate(entry.changed_at)}
                            subtitle={`${scopeShortLabel(entry.previous_value)} → ${scopeShortLabel(entry.new_value)}`}
                            media={{ icon: 'history' }}
                            details={
                              entry.reason
                                ? [
                                    {
                                      label: 'Razón',
                                      value: entry.reason,
                                      icon: 'message-square',
                                    },
                                  ]
                                : []
                            }
                            footerLabel="Usuario"
                            footerValue={
                              entry.changed_by_user_id
                                ? `#${entry.changed_by_user_id}`
                                : 'Sistema'
                            }
                          />
                        </View>
                      ))}
                    </View>
                  )}
                </View>
              </Card>
            </View>
          </>
        ) : null}

        <View style={{ height: spacing[12] }} />
      </ScrollView>

      {/* Wizard */}
      {pendingTarget ? (
        <ChangeScopeWizard
          visible={wizardOpen}
          currentScope={current}
          targetScope={pendingTarget}
          onClose={() => {
            setWizardOpen(false);
            setPendingTarget(null);
          }}
          onApplied={onApplied}
        />
      ) : null}
    </OrgPageContainer>
  );
}

// ───────────────────────────────────────────────────────────────────────
// Sub-component: ScopeCardButton (paridad 1:1 con scope card web)
// ───────────────────────────────────────────────────────────────────────

interface ScopeCardButtonProps {
  value: OperatingScopeValue;
  active: boolean;
  disabled: boolean;
  onPress: () => void;
}

function ScopeCardButton({ value, active, disabled, onPress }: ScopeCardButtonProps) {
  const label = scopeShortLabel(value) === 'Tienda' ? 'Por tienda' : scopeShortLabel(value);
  const description = SCOPE_DESCRIPTIONS[value];
  const iconBg = SCOPE_ICON_BG[value];
  const iconFg = SCOPE_ICON_FG[value];

  return (
    <Pressable
      onPress={onPress}
      disabled={disabled}
      style={({ pressed }) => [
        styles.scopeCard,
        active && styles.scopeCardActive,
        !active && !disabled && pressed && styles.scopeCardHover,
        disabled && !active && styles.scopeCardDisabled,
      ]}
    >
      <View style={styles.scopeCardRow}>
        <View
          style={[
            styles.scopeIconWrap,
            { backgroundColor: iconBg },
          ]}
        >
          <Icon name={SCOPE_ICONS[value]} size={22} color={iconFg} />
        </View>

        <View style={styles.scopeCardBody}>
          <View style={styles.scopeLabelRow}>
            <Text
              style={[styles.scopeLabel, active && styles.scopeLabelActive]}
              numberOfLines={1}
            >
              {label}
            </Text>
            {active ? (
              <View style={styles.activePill}>
                <Text style={styles.activePillText}>Activo</Text>
              </View>
            ) : null}
          </View>
          <Text
            style={[styles.scopeDesc, disabled && styles.scopeDescDisabled]}
            numberOfLines={4}
          >
            {description}
          </Text>
        </View>
      </View>
    </Pressable>
  );
}

// ───────────────────────────────────────────────────────────────────────
// Helpers
// ───────────────────────────────────────────────────────────────────────

function extractErrorMessage(err: any): string {
  const payload = err?.error ?? err?.response?.data;
  if (payload) {
    const msg = payload?.message;
    if (Array.isArray(msg)) {
      const joined = msg.filter(Boolean).map(String).join('. ');
      if (joined) return joined;
    }
    if (typeof msg === 'string' && msg.trim()) return msg;
  }
  const status = err?.status ?? err?.response?.status;
  if (status === 0 || status === undefined) {
    return 'No se pudo conectar con el servidor.';
  }
  if (status === 401 || status === 403) {
    return 'No tienes permisos para ver el modo operativo. Si los permisos se actualizaron recientemente, cierra sesión y vuelve a iniciar.';
  }
  return 'No se pudo cargar el modo operativo de la organización.';
}

// ───────────────────────────────────────────────────────────────────────
// Styles — paridad 1:1 con clases Tailwind del web
// ───────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  // ── Sticky sub-header (espejo del <app-sticky-header> web) ──
  stickySubHeader: {
    backgroundColor: colors.card,
    borderBottomWidth: 1,
    borderBottomColor: colorScales.gray[200],
    ...shadows.sm,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1.5],
  },
  titleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    flex: 1,
  },
  backBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: borderRadius.md,
  },
  titleText: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold,
    color: colorScales.gray[900],
  },
  subtitle: {
    fontSize: typography.fontSize.xs,
    color: colorScales.gray[500],
    marginTop: 2,
  },

  // ── Body ──
  scrollContent: {
    padding: spacing[4],
  },

  // loading
  loadingBox: {
    alignItems: 'center',
    paddingVertical: spacing[10],
    gap: spacing[2],
  },
  loadingText: {
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[500],
  },

  // danger alert (paridad con <app-alert-banner variant="danger">)
  dangerAlert: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    backgroundColor: colorScales.red[50],
    borderRadius: borderRadius.md,
    padding: spacing[3],
    marginBottom: spacing[4],
    borderWidth: 1,
    borderColor: colorScales.red[200],
  },
  dangerAlertText: {
    flex: 1,
    fontSize: typography.fontSize.sm,
    color: colorScales.red[700],
  },
  retryLink: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colorScales.red[700],
    textDecorationLine: 'underline',
  },

  // sections
  section: {
    marginBottom: spacing[4],
  },
  cardBody: {
    padding: spacing[4],
    gap: spacing[4],
  },

  // eyebrow labels (text-xs font-bold uppercase tracking-wider text-gray-400)
  eyebrow: {
    fontSize: 10,
    fontWeight: '700' as const,
    color: colorScales.gray[400],
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: spacing[2],
  },

  // current header
  currentHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing[3],
  },
  currentHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  currentTitle: {
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.semibold,
    color: colorScales.gray[900],
    marginTop: 2,
  },
  currentDescription: {
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[500],
    marginTop: spacing[1],
    lineHeight: 18,
  },
  partnerBadgeWrap: {
    flexShrink: 0,
  },

  // partner alert (paridad con <app-alert-banner variant="warning" icon="lock">)
  partnerAlert: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing[2],
    backgroundColor: colorScales.amber[50],
    borderRadius: borderRadius.md,
    padding: spacing[3],
    borderWidth: 1,
    borderColor: colorScales.amber[200],
  },
  partnerAlertText: {
    flex: 1,
    fontSize: typography.fontSize.sm,
    color: colorScales.amber[700],
    lineHeight: 18,
  },
  partnerAlertStrong: {
    fontWeight: typography.fontWeight.bold,
  },

  // scope toggle
  scopeSection: {},
  scopeCardsRow: {
    gap: spacing[3],
  },
  scopeCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colorScales.gray[200],
    borderRadius: 16, // web: rounded-2xl = 1rem
    padding: spacing[4],
  },
  scopeCardActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(47, 111, 78, 0.05)', // primary/5
    borderWidth: 1,
    ...shadows.sm,
    // ring-1 ring-primary/20 — simulado con border secundario
  },
  scopeCardHover: {
    borderColor: 'rgba(47, 111, 78, 0.5)', // primary/50
    ...shadows.md,
  },
  scopeCardDisabled: {
    opacity: 0.7,
  },
  scopeCardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing[3],
  },
  scopeIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12, // web: rounded-xl = 0.75rem
    alignItems: 'center',
    justifyContent: 'center',
  },
  scopeCardBody: {
    flex: 1,
    minWidth: 0,
  },
  scopeLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    flexWrap: 'wrap',
  },
  scopeLabel: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    color: colorScales.gray[900],
  },
  scopeLabelActive: {
    color: colorScales.gray[900],
  },
  scopeDesc: {
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[500],
    marginTop: spacing[2],
    lineHeight: 18,
  },
  scopeDescDisabled: {
    color: colorScales.gray[400],
  },
  activePill: {
    backgroundColor: colorScales.green[100],
    paddingHorizontal: spacing[2],
    paddingVertical: 2,
    borderRadius: borderRadius.full,
  },
  activePillText: {
    fontSize: 10,
    fontWeight: typography.fontWeight.bold,
    color: colorScales.green[700],
  },

  // actions
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },

  // audit log
  auditHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  auditHeaderTitle: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    color: colorScales.gray[900],
  },
  emptyAudit: {
    alignItems: 'center',
    paddingVertical: spacing[8],
    gap: spacing[2],
  },
  emptyAuditText: {
    fontSize: typography.fontSize.sm,
    color: colorScales.gray[500],
    textAlign: 'center',
  },
  auditList: {
    gap: spacing[2],
  },
  auditItem: {},
});

// apps/frontend/src/app/private/modules/organization/settings/operating-scope/operating-scope.component.ts
import {
  Component,
  DestroyRef,
  computed,
  inject,
  signal,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { HttpErrorResponse } from '@angular/common/http';

import {
  AlertBannerComponent,
  BadgeComponent,
  ButtonComponent,
  CardComponent,
  IconComponent,
  ItemListCardConfig,
  ResponsiveDataViewComponent,
  SpinnerComponent,
  StickyHeaderComponent,
  TableColumn,
} from '../../../../../shared/components';
import { formatDateOnlyUTC } from '../../../../../shared/utils/date.util';
import { ChangeScopeWizardComponent } from './components/change-scope-wizard.component';
import {
  OperatingScopeApplyResult,
  OperatingScopeAuditLogEntry,
  OperatingScopeCurrentState,
  OperatingScopeValue,
  OperatingScopeWizardService,
} from './services/operating-scope.service';

@Component({
  selector: 'app-operating-scope',
  standalone: true,
  imports: [
    AlertBannerComponent,
    BadgeComponent,
    ButtonComponent,
    CardComponent,
    ChangeScopeWizardComponent,
    IconComponent,
    ResponsiveDataViewComponent,
    SpinnerComponent,
    StickyHeaderComponent,
  ],
  templateUrl: './operating-scope.component.html',
  styleUrl: './operating-scope.component.scss',
})
export class OperatingScopeComponent {
  private readonly service = inject(OperatingScopeWizardService);
  private readonly destroyRef = inject(DestroyRef);

  // ---------- state ----------
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);
  readonly state = signal<OperatingScopeCurrentState | null>(null);
  readonly wizardOpen = signal(false);
  readonly pendingTarget = signal<OperatingScopeValue>('STORE');

  // ---------- computed ----------
  readonly current = computed<OperatingScopeValue>(
    () => this.state()?.current ?? 'STORE',
  );
  readonly isPartner = computed(() => this.state()?.is_partner === true);
  readonly editable = computed(
    () => this.state()?.editable === true && !this.loading(),
  );
  readonly auditLog = computed<OperatingScopeAuditLogEntry[]>(
    () => this.state()?.audit_log_recent ?? [],
  );

  readonly currentLabel = computed(() =>
    this.current() === 'ORGANIZATION'
      ? 'Organización (consolidado)'
      : 'Por tienda',
  );

  // ---------- audit log table/card config ----------
  readonly auditColumns: TableColumn[] = [
    {
      key: 'changed_at',
      label: 'Fecha',
      sortable: true,
      priority: 1,
      transform: (value: string) => this.formatTimestamp(value),
    },
    {
      key: 'changes',
      label: 'Cambio',
      priority: 1,
      transform: (_value: any, item: OperatingScopeAuditLogEntry) =>
        `${this.scopeLabel(item.previous_value)} → ${this.scopeLabel(item.new_value)}`,
    },
    {
      key: 'changed_by_user_id',
      label: 'Usuario',
      priority: 2,
      transform: (value: number | null) =>
        value ? `#${value}` : 'Sistema',
    },
    {
      key: 'reason',
      label: 'Razón',
      priority: 3,
      defaultValue: '—',
      transform: (value: string | null) => value?.trim() || '—',
    },
  ];

  readonly auditCardConfig: ItemListCardConfig = {
    titleKey: 'changed_at',
    titleTransform: (item: OperatingScopeAuditLogEntry) =>
      this.formatTimestamp(item.changed_at),
    subtitleKey: 'new_value',
    subtitleTransform: (item: OperatingScopeAuditLogEntry) =>
      `${this.scopeLabel(item.previous_value)} → ${this.scopeLabel(item.new_value)}`,
    avatarFallbackIcon: 'history',
    avatarShape: 'circle',
    footerKey: 'changed_by_user_id',
    footerLabel: 'Usuario',
    footerTransform: (value: number | null) =>
      value ? `#${value}` : 'Sistema',
    detailKeys: [
      { key: 'reason', label: 'Razón', icon: 'message-square' },
    ],
  };

  constructor() {
    this.loadCurrent();
  }

  loadCurrent(): void {
    this.loading.set(true);
    this.error.set(null);

    this.service
      .getCurrent()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (value) => {
          this.state.set(value);
          this.loading.set(false);
        },
        error: (err: HttpErrorResponse) => {
          this.loading.set(false);
          this.error.set(this.humanError(err));
        },
      });
  }

  // ---------- actions ----------
  selectScope(target: OperatingScopeValue): void {
    if (!this.editable() || target === this.current()) return;
    this.pendingTarget.set(target);
    this.wizardOpen.set(true);
  }

  openWizardForToggle(): void {
    if (!this.editable()) return;
    const target: OperatingScopeValue =
      this.current() === 'ORGANIZATION' ? 'STORE' : 'ORGANIZATION';
    this.pendingTarget.set(target);
    this.wizardOpen.set(true);
  }

  onApplied(_result: OperatingScopeApplyResult): void {
    // Refresh state so the audit log + current scope reflect reality.
    this.loadCurrent();
  }

  // ---------- formatting helpers ----------
  formatTimestamp(value: string): string {
    if (!value) return '-';
    try {
      const d = new Date(value);
      // Display in es-CO locale; backend stores UTC, browser converts to org/user TZ.
      return d.toLocaleString('es-CO', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return formatDateOnlyUTC(value);
    }
  }

  scopeLabel(value: OperatingScopeValue | null | undefined): string {
    if (!value) return '—';
    return value === 'ORGANIZATION' ? 'Organización' : 'Por tienda';
  }

  private humanError(err: HttpErrorResponse): string {
    const status = err?.status;
    const code: string | undefined = err?.error?.error_code;
    if (status === 0 || status === undefined) {
      return 'No se pudo conectar con el servidor.';
    }
    if (code === 'AUTH_PERM_001' || status === 401 || status === 403) {
      return 'No tienes permisos para ver el modo operativo. Si los permisos se actualizaron recientemente, cierra sesión y vuelve a iniciar.';
    }
    const payload: any = err?.error;
    const msg = payload?.message;
    if (Array.isArray(msg)) return msg.filter(Boolean).join('. ');
    if (typeof msg === 'string' && msg.trim()) return msg;
    if (typeof payload === 'string' && payload.trim()) return payload;
    return 'No se pudo cargar el modo operativo de la organización.';
  }

  scopeCardClasses(scope: OperatingScopeValue): string {
    const selected = this.current() === scope;
    return [
      'w-full rounded-2xl border p-5 text-left transition-all duration-200',
      'focus:outline-none focus:ring-2 focus:ring-primary/40',
      this.editable() ? 'hover:-translate-y-0.5' : 'cursor-not-allowed opacity-70',
      selected
        ? 'border-primary bg-primary/5 shadow-sm ring-1 ring-primary/20'
        : 'border-[var(--color-border)] bg-white hover:border-primary/50 hover:shadow-md',
    ].join(' ');
  }
}

<div class="w-full space-y-6">
  <app-sticky-header
    title="Modo operativo"
    subtitle="Define si la organización opera por tienda o de forma consolidada"
    icon="settings"
    [showBackButton]="true"
    backRoute="/admin/config/operations"
  ></app-sticky-header>

  @if (loading()) {
    <div class="flex justify-center py-12">
      <app-spinner size="lg" text="Cargando modo operativo..."></app-spinner>
    </div>
  } @else {
    @if (error()) {
      <app-alert-banner variant="danger" icon="alert-circle">
        {{ error() }}
        <button class="ml-3 font-semibold underline" (click)="loadCurrent()">
          Reintentar
        </button>
      </app-alert-banner>
    }

    @if (state()) {
      <!-- Current scope card -->
      <app-card [responsivePadding]="true">
        <div class="space-y-4">
          <div
            class="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"
          >
            <div>
              <p
                class="text-xs font-bold uppercase tracking-wider text-gray-400"
              >
                Modo operativo actual
              </p>
              <h2
                class="mt-1 text-xl font-semibold text-[var(--color-text-primary)]"
              >
                {{ currentLabel() }}
              </h2>
              <p class="mt-1 text-sm text-[var(--color-text-secondary)]">
                Aplica a inventario, contabilidad, compras, valoración y
                reportes de la organización.
              </p>
            </div>

            @if (isPartner()) {
              <app-badge variant="warning" size="md">
                Partner — bloqueado
              </app-badge>
            }
          </div>

          @if (isPartner()) {
            <app-alert-banner variant="warning" icon="lock">
              Esta organización es partner de Vendix. El modo operativo está
              fijado en <strong>Por tienda</strong> y no puede modificarse desde
              esta pantalla.
            </app-alert-banner>
          }

          <!-- Scope toggle (segmented) -->
          <div>
            <p
              class="mb-3 text-xs font-bold uppercase tracking-wider text-gray-400"
            >
              Selecciona el modo operativo
            </p>

            <div class="grid grid-cols-1 gap-4 lg:grid-cols-2">
              <button
                type="button"
                [class]="scopeCardClasses('STORE')"
                [disabled]="!editable()"
                (click)="selectScope('STORE')"
              >
                <div class="flex items-start gap-4">
                  <div class="mt-1 rounded-xl bg-blue-50 p-3 text-blue-600">
                    <app-icon name="store" [size]="22"></app-icon>
                  </div>
                  <div class="min-w-0 flex-1">
                    <div class="flex items-center gap-2">
                      <h3
                        class="font-semibold text-[var(--color-text-primary)]"
                      >
                        Por tienda
                      </h3>
                      @if (current() === "STORE") {
                        <span
                          class="rounded-full bg-green-100 px-2 py-0.5 text-xs font-semibold text-green-700"
                        >
                          Activo
                        </span>
                      }
                    </div>
                    <p class="mt-2 text-sm text-[var(--color-text-secondary)]">
                      Cada tienda maneja sus propios proveedores, ubicaciones,
                      inventario, compras, contabilidad y reportes operativos.
                    </p>
                  </div>
                </div>
              </button>

              <button
                type="button"
                [class]="scopeCardClasses('ORGANIZATION')"
                [disabled]="!editable()"
                (click)="selectScope('ORGANIZATION')"
              >
                <div class="flex items-start gap-4">
                  <div class="mt-1 rounded-xl bg-purple-50 p-3 text-purple-600">
                    <app-icon name="building" [size]="22"></app-icon>
                  </div>
                  <div class="min-w-0 flex-1">
                    <div class="flex flex-wrap items-center gap-2">
                      <h3
                        class="font-semibold text-[var(--color-text-primary)]"
                      >
                        Organización (consolidado)
                      </h3>
                      @if (current() === "ORGANIZATION") {
                        <span
                          class="rounded-full bg-green-100 px-2 py-0.5 text-xs font-semibold text-green-700"
                        >
                          Activo
                        </span>
                      }
                    </div>
                    <p class="mt-2 text-sm text-[var(--color-text-secondary)]">
                      La organización consolida operación, valoración,
                      contabilidad y reportes entre tiendas.
                    </p>
                  </div>
                </div>
              </button>
            </div>
          </div>

          <div class="flex justify-end">
            <app-button
              variant="primary"
              [disabled]="!editable()"
              (click)="openWizardForToggle()"
            >
              Cambiar modo operativo
            </app-button>
          </div>
        </div>
      </app-card>

      <!-- Audit log -->
      <app-card [responsivePadding]="true">
        <div class="space-y-3">
          <div class="flex items-center gap-2">
            <app-icon name="history" [size]="18" class="text-primary"></app-icon>
            <h3 class="font-semibold text-[var(--color-text-primary)]">
              Historial reciente
            </h3>
          </div>

          <app-responsive-data-view
            [data]="auditLog()"
            [columns]="auditColumns"
            [cardConfig]="auditCardConfig"
            [loading]="loading()"
            [sortable]="true"
            emptyMessage="Sin cambios registrados"
            emptyIcon="history"
          ></app-responsive-data-view>
        </div>
      </app-card>
    }
  }

  <!-- Wizard modal -->
  @if (state()) {
    <app-change-scope-wizard
      [(isOpen)]="wizardOpen"
      [currentScope]="current()"
      [targetScope]="pendingTarget()"
      (applied)="onApplied($event)"
    ></app-change-scope-wizard>
  }
</div>
